name: ✨ Feature Request
about: Suggest an idea or a new feature for the project.
title: "GHS-Feature-"
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the feature.
    validations:
      required: true
