name: Feature Request
description: Suggest a new feature or enhancement.
title: "GHS-FEATURE: "
labels: ["enhancement", "triage"]
assignees:
  - # Optional: Add a default assignee username here
body:
  - type: markdown
    attributes:
      value: "### Thanks for suggesting a new idea!"
  - type: textarea
    id: description
    attributes:
      label: Is your feature request related to a problem?
      description: "A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]"
      placeholder: "A clear and concise description of the problem."
    validations:
      required: false
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: "A clear and concise description of what you want to happen."
      placeholder: "A clear and concise description of the solution."
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: "A clear and concise description of any alternative solutions or features you've considered."
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: "Add any other context or screenshots about the feature request here."
    validations:
      required: false
