# name: Task
# description: Create a general task or a maintenance item.
# title: "GHS-TASK: "
# labels: ["task", "triage"]
# assignees:
#   - # Optional: Add a default assignee username here
# body:
#   - type: textarea
#     id: task_description
#     attributes:
#       label: Task Description
#       description: "Please provide a clear description of the task."
#       placeholder: "Describe the task here..."
#     validations:
#       required: true
#   - type: textarea
#     id: subtasks
#     attributes:
#       label: Subtasks (Optional)
#       description: "List any subtasks or steps that are part of this task."
#       placeholder: |
#         - [ ] Subtask 1
#         - [ ] Subtask 2
#     validations:
#       required: false
