name: Auto Create Branch from Issue

on:
  issues:
    types: [opened]

jobs:
  create_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Issue Info
        id: extract
        run: |
          TITLE="${{ github.event.issue.title }}"
          ISSUE_ID="${{ github.event.issue.number }}"
          LABELS=$(echo '${{ toJson(github.event.issue.labels) }}' | jq -r '.[].name')

          # Determine branch type based on label
          if echo "$LABELS" | grep -qi "bug"; then
            PREFIX="GHS-BUG"
          elif echo "$LABELS" | grep -qi "feature"; then
            PREFIX="GHS-FEATURE"
          elif echo "$LABELS" | grep -qi "task"; then
            PREFIX="GHS-TASK"
          else
            PREFIX="GHS-MISC"
          fi

          # Sanitize title for branch name (lowercase, replace spaces & special chars)
          SAFE_TITLE=$(echo "$TITLE" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/-/g')

          echo "BRANCH_NAME=${PREFIX}-${SAFE_TITLE}-${ISSUE_ID}" >> $GITHUB_ENV

      - name: Create Branch via API
        run: |
          DEFAULT_BRANCH=$(curl -s \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }} \
            | jq -r .default_branch)

          SHA=$(curl -s \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/git/refs/heads/$DEFAULT_BRANCH \
            | jq -r .object.sha)

          curl -s \
            -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{\"ref\":\"refs/heads/${BRANCH_NAME}\",\"sha\":\"$SHA\"}" \
            https://api.github.com/repos/${{ github.repository }}/git/refs
