name: Create Issue Branch (Demo)

on:
  issues:
    types: [assigned]

jobs:
  create_branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create branch
        run: |
          branch_name="issue-${{ github.event.issue.number }}"
          echo "Creating branch: $branch_name"
          git checkout -b "$branch_name"

      - name: Push branch
        run: |
          branch_name="issue-${{ github.event.issue.number }}"
          git push origin "$branch_name"
