name: Check Branch Name

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name format
        run: |
          branch_name="${GITHUB_REF##*/}"
          echo "Branch name: $branch_name"
          
          # Enforce pattern: GHS-BUG-<number> or GHS-TASK-<number> or GHS-FEATURE-<number>
          if [[ ! "$branch_name" =~ ^GHS-(BUG|TASK|FEATURE)-[0-9]+$ ]]; then
            echo "❌ Branch name '$branch_name' does not follow the required format: GHS-(BUG|TASK|FEATURE)-<number>"
            exit 1
          fi
          
          echo "✅ Branch name format is correct."
