name: Create Issue Branch

on:
  issues:
    types: [assigned]

jobs:
  determine_branch_name:
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps.set_name.outputs.branch_name }}
    steps:
      - id: set_name
        name: Set dynamic branch name from issue type in title
        run: |
          issue_title="${{ github.event.issue.title }}"
          type=$(echo "$issue_title" | awk '{print tolower($1)}') # first word

          case "$type" in
            bug)
              prefix="GHS-BUG"
              ;;
            task)
              prefix="GHS-TASK"
              ;;
            feature)
              prefix="GHS-FEATURE"
              ;;
            *)
              prefix="GHS-FEATURE"
              ;;
          esac

          branch_name="${prefix}"
          echo "Branch name will be: $branch_name"
          echo "branch_name=$branch_name" >> $GITHUB_OUTPUT

  create_branch:
    needs: determine_branch_name
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write
    steps:
      - name: Create an issue branch
        uses: robv-oss/actions-create-issue-branch@v2.2.0
        with:
          branchName: ${{ needs.determine_branch_name.outputs.branch_name }}
