name: Check PR Comments

on:
  pull_request:
    types: [opened, synchronize, reopened] # Triggers on PR activity

jobs:
  check_conversations:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read # Needed to read PR details and comments
      statuses: write # Needed to set the status check result (success/failure)
    
    steps:
      - name: Check for Unresolved Comments (Custom Logic)
        id: comment_check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Use the GitHub CLI to get the number of unresolved review comments
          # Note: The GH CLI is available on GitHub-hosted runners
          # We search for 'UNRESOLVED' review threads.
          UNRESOLVED_COUNT=$(gh api \
            -H "Accept: application/vnd.github.v3+json" \
            /repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews \
            | jq '.[] | .state' \
            | grep -c 'COMMENTED')

          echo "Found $UNRESOLVED_COUNT review comments that are not resolved or approved."

          if [[ $UNRESOLVED_COUNT -gt 0 ]]; then
            echo "::error::The PR has $UNRESOLVED_COUNT unresolved review comment threads. Please resolve them."
            exit 1 # Fail the job if unresolved comments exist
          else
            echo "All review comments are either resolved or the PR is approved."
          fi
          
      # The job succeeds if the 'run' script exits with 0 (default)
      # The job fails if the 'run' script exits with 1 (as set in the 'else' block)
